<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    
    <AssemblyName>Minicraft.Applications.Client</AssemblyName>
    <RootNamespace>Minicraft.Applications.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" />
    <PackageReference Include="Silk.NET.Input.Sdl" />
    <PackageReference Include="Silk.NET.Windowing" />
    <PackageReference Include="Silk.NET.Windowing.Sdl" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Engine\Engine.csproj" />
    <ProjectReference Include="..\..\Rendering\Rendering.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="..\..\..\assets\**\*">
      <Link>assets\%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
